# Generated by Django 3.0.6 on 2020-05-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200, verbose_name='Task Description')),
                ('refresh_days_field', models.CharField(max_length=7, verbose_name='Days of the week to refresh the task')),
                ('refresh_time', models.TimeField(verbose_name='Time of day to refresh task')),
                ('task_done', models.BooleanField(default=False, verbose_name='Is the task done')),
            ],
        ),
    ]
