# Generated by Django 3.0.6 on 2020-06-06 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='last_refreshed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='refresh_days_field',
            field=models.CharField(max_length=7, verbose_name='Days of the week to reset task'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='refresh_time',
            field=models.TimeField(verbose_name='Time of day to reset task'),
        ),
    ]
