# Generated by Django 3.0.6 on 2020-06-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_auto_20200606_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='last_refreshed',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Last time the task was refreshed'),
        ),
    ]
