# Generated by Django 3.0.7 on 2020-06-11 16:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_auto_20200606_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='last_refreshed',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 16, 8, 36, 143384, tzinfo=utc), verbose_name='Last time the task was refreshed'),
        ),
    ]
