# Generated by Django 3.0.6 on 2020-06-13 03:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_auto_20200611_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mod name')),
                ('link', models.CharField(max_length=200, verbose_name='Link to mod')),
                ('mod_added', models.BooleanField(default=False, verbose_name='Is the mod added')),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='last_refreshed',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 3, 5, 26, 936809, tzinfo=utc), verbose_name='Last time the task was refreshed'),
        ),
    ]
